### ISSUE TITLE
Lingebra - Diagonalizovatelnost operátoru

### ISSUE THREAD

**Issue by riskin88** [Morcinus/FIT-Flashcards#1]
ta věta 7.35 není přímo definice, naopak je to podle mě ta nutná a postačující podmínka
![image](https://user-images.githubusercontent.com/43642452/119346430-7b076600-bc9a-11eb-9b1d-ede81838182c.png)

definice je toto:
![image](https://user-images.githubusercontent.com/43642452/119346605-b6099980-bc9a-11eb-9a83-ba805889d8e8.png)

**Comment by Morcinus** [comment]
No jo, pravda. Jsem tam tu definici zapomněl dát. 👍
